function build = run_embedded_foc_codegen(model, varargin)
%RUN_EMBEDDED_FOC_CODEGEN Audit-gated, explicitly authorized slbuild.
%
% build = run_embedded_foc_codegen("motor_control.slx", ...
%     "ConfirmBuild", true, ...
%     "ControllerPath", "motor_control/FOC_Controller")
%
% The function fails closed: ConfirmBuild must be true and the deployment
% audit must contain zero FAIL results before slbuild is called.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, 'model', @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(parser, 'ControllerPath', '', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(parser, 'ConfirmBuild', false, ...
    @(x) islogical(x) && isscalar(x));
addParameter(parser, 'AuditOutputFile', '', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(parser, 'GenericAuditOutputFile', '', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(parser, 'Verbose', true, ...
    @(x) islogical(x) && isscalar(x));
parse(parser, model, varargin{:});
opts = parser.Results;

if ~opts.ConfirmBuild
    error('run_embedded_foc_codegen:BuildNotAuthorized', ...
        ['Build authorization is required. Re-run only after explicit user ' ...
        'consent with ConfirmBuild=true.']);
end

if exist('audit_simulink_model', 'file') ~= 2 || ...
        exist('audit_embedded_foc_model', 'file') ~= 2
    error('run_embedded_foc_codegen:AuditorNotInstalled', ...
        ['The simulink-model-auditor Skill scripts are required. Add its ' ...
        'scripts folder to the MATLAB path before requesting a build.']);
end

genericScope = char(opts.ControllerPath);
genericAudit = audit_simulink_model(model, ...
    'Scope', genericScope, ...
    'Profile', 'deployment', ...
    'Compile', true, ...
    'Verbose', opts.Verbose, ...
    'OutputFile', opts.GenericAuditOutputFile);
focAudit = audit_embedded_foc_model(model, ...
    'ControllerPath', opts.ControllerPath, ...
    'Profile', 'deployment', ...
    'Compile', true, ...
    'Verbose', opts.Verbose, ...
    'OutputFile', opts.AuditOutputFile);
failureCount = genericAudit.summary.fail + focAudit.summary.fail;
if failureCount > 0
    error('run_embedded_foc_codegen:AuditFailed', ...
        ['Generic and FOC deployment audits have %d total FAIL result(s); ' ...
        'slbuild was not called.'], failureCount);
end

modelDir = fileparts(focAudit.file);
oldDir = pwd;
dirCleanup = onCleanup(@() cd(oldDir));
if ~isempty(modelDir)
    cd(modelDir);
end

wasLoaded = bdIsLoaded(focAudit.model);
if ~wasLoaded
    load_system(focAudit.file);
end
modelCleanup = onCleanup(@() closeIfOpenedForBuild(focAudit.model, wasLoaded));

target = focAudit.model;
if ~isempty(opts.ControllerPath)
    target = char(opts.ControllerPath);
elseif ~isempty(focAudit.controller.path)
    target = focAudit.controller.path;
end

startedAt = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX'));
buildOutput = slbuild(target);
build = struct( ...
    'succeeded', true, ...
    'target', target, ...
    'startedAtUtc', startedAt, ...
    'genericAuditSummary', genericAudit.summary, ...
    'focAuditSummary', focAudit.summary, ...
    'genericAuditReadiness', genericAudit.readiness, ...
    'focAuditReadiness', focAudit.readiness, ...
    'buildOutput', buildOutput);

delete(modelCleanup);
delete(dirCleanup);
end

function closeIfOpenedForBuild(modelName, wasLoaded)
if ~wasLoaded && bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
